### ISSUE TITLE
Mockup Traffic Light Waypoint publisher

### ISSUE THREAD

**Issue by ahmedkhalaf** [ahmedkhalaf/CarND-Capstone#2]
a static set of waypoint sequence is published /base_waypoints as if an obstacle or Traffic Light was detected (ROS Node using ros/src/waypoint_loader/ providing waypoints based on time/location? or just a replay something derived from ROS bag Traffic Light Detection Test Video from Udacity?)

**Comment by ahmedkhalaf** [comment]
Depending on the implementation, this might be redundant to #5 .. please note that simulator already provides Traffic light state and stopping line.

**Comment by BenLJM** [comment]
Ok, then I will work on #6
