### ISSUE TITLE
Traffic Light Detection Part1 - Detection

### ISSUE THREAD

**Issue by ahmedkhalaf** [ahmedkhalaf/CarND-Capstone#4]
Detect the traffic light and its color from the /image_color. The topic /vehicle/traffic_lights contains the exact location and status of all traffic lights in simulator, so you can test your output.

**Comment by kjr21362** [comment]
Changes checked in to tl_detection branch. Two models couldn't be uploaded to the repo. For now, we can download them from https://github.com/kjr21362/CarND-Capstone/tree/master/ros/src/tl_detector.
