### ISSUE TITLE
Traffic Light Detection Part2 - Waypoint publishing

### ISSUE THREAD

**Issue by ahmedkhalaf** [ahmedkhalaf/CarND-Capstone#6]
Once you have correctly identified the traffic light and determined its position, you can convert it to a waypoint index and publish it.

For testing, please refer to:  [Real world Testing using rosbag](https://github.com/ahmedkhalaf/CarND-Capstone#real-world-testing)

**Comment by ahmedkhalaf** [comment]
I tried to test master branch (along with DBW node implementation), I got this on the consol running "roslaunch launch/styx.launch"
Am I missing something? or could this be a problem in TL detector  or waypoint publisher?
What do you think @hualishiwo and @LJM2018 ?

process[tl_detector-8]: started with pid [1369]
(1140) accepted ('127.0.0.1', 41533)
Traceback (most recent call last):
  File "/home/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 147, in <module>
    WaypointUpdater()
  File "/home/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 49, in __init__
    self.loop()
  File "/home/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 55, in loop
    self.publish_waypoints()   
TypeError: publish_waypoints() takes exactly 2 arguments (1 given)
[waypoint_updater-7] process has died [pid 1331, exit code 1, cmd /home/workspace/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py __name:=waypoint_updater __log:=/root/.ros/log/cb81b676-594b-11e9-9a8f-0242ac110002/waypoint_updater-7.log].
log file: /root/.ros/log/cb81b676-594b-11e9-9a8f-0242ac110002/waypoint_updater-7*.log

**Comment by danielwo** [comment]
Sorry I haven't been around more. I have been testing everything trying to get things to work. I'll reply with some issues I'm having in other threads.

Your particular problem here is 
def publish_waypoints(self, closest_idx):
should be
def publish_waypoints(self):

**Comment by ahmedkhalaf** [comment]
Thanks @danielwo .. I fixed this issue in changeset 9925a1e

**Comment by ahmedkhalaf** [comment]
DBW node is able to drive the car in simulator normally as long as Camera is disabled (TL states are not updated)
Even when classifier followed light.state coming from simulator, waypoints seem to be still not updating correctly (the green trail of pearls still showed the first ones).
Also, the car didn't return to the first waypoint but kept driving crazy
After merging master branch I also added few test options for testing on dbw_branch
In changeset 653dbee "Added DISABLE_CLASSIFIER and CLASSIFIER_ALWAYS_GREEN for testing"
